name: app3-backend-build

on:
  push:
    branches: [main]
    paths:
      - "apps/app3/backend/**"
      - ".github/workflows/app3-backend.yaml"
      - ".github/workflows/build-image.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  image:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/build-image.yaml
    with:
      name: app3-backend
      context: apps/app3/backend
      manifest: app-deployments/app3/backend-deployment.yaml